# Generated by Django 5.2.3 on 2025-06-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todotask',
            fields=[
                ('user_Id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Task', models.CharField(max_length=100)),
                ('starts', models.DateField()),
                ('ends', models.DateField()),
                ('priority', models.CharField(choices=[('low', 'low'), ('moderate', 'moderate'), ('high', 'high')], max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
