# Generated by Django 5.2.3 on 2025-06-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptodo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todotask',
            name='user_Id',
        ),
        migrations.AddField(
            model_name='todotask',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
