# Generated by Django 5.2.3 on 2025-06-29 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptodo', '0003_todotask_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todotask',
            options={'ordering': ['-priority']},
        ),
    ]
