# Generated by Django 5.2.3 on 2025-06-29 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptodo', '0004_alter_todotask_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todotask',
            options={'ordering': ['priority']},
        ),
    ]
